from odoo import models, api

class StockReport(models.Model):
    _name = 'stock.report'
    _description = 'Stock Report'

    @api.model
    def send_daily_stock_report(self):

        products = self.env['product.product'].search([])

        # build HTML manually
        rows = ""
        for p in products:
            rows += f"""
                <tr>
                    <td>{p.name}</td>
                    <td>{p.qty_available}</td>
                </tr>
            """

        body = f"""
        <div style="font-family: Arial; padding: 10px;">
            <h2 style="color:#2E86C1;">📦 Daily Stock Report</h2>

            <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
                <tr style="background-color:#f2f2f2;">
                    <th>Product</th>
                    <th>Available Quantity</th>
                </tr>
                {rows}
            </table>

            <br/>
            <p style="color:gray;">Auto-generated by Odoo</p>
        </div>
        """
        store_manager = self.env['hr.employee'].search([
            ('job_title', '=', 'Store Manager'),
            ('department_id.name', '=', 'Store Department')
        ], limit=1)

        email = store_manager.user_id.partner_id.email if store_manager.user_id else ''

        mail_values = {
            'subject': 'Daily Stock Report',
            'body_html': body,
            'email_to': email,
        }
        

        self.env['mail.mail'].create(mail_values).send()

    # Production Summary Report
    @api.model
    def send_weekly_production_report(self):

        productions = self.env['mrp.production'].search([
            ('state', '=', 'done')
        ])

        rows = ""
        total_qty = 0

        for mo in productions:
            rows += f"""
                <tr>
                    <td>{mo.name}</td>
                    <td>{mo.product_id.name}</td>
                    <td>{mo.qty_producing or mo.product_qty}</td>
                    <td>{mo.date_finished}</td>
                </tr>
            """
            total_qty += mo.qty_producing or mo.product_qty

        body = f"""
        <div style="font-family: Arial; padding: 10px;">
            <h2 style="color:#28B463;">🏭 Weekly Production Summary</h2>

            <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
                <tr style="background-color:#f2f2f2;">
                    <th>MO</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Finished Date</th>
                </tr>
                {rows}
            </table>

            <br/>
            <b>Total Production:</b> {total_qty}

            <p style="color:gray;">Auto-generated by Odoo</p>
        </div>
        """
        # store_manager = self.env['hr.employee'].search([
        #     ('job_title', '=', 'Store Manager'),
        #     ('department_id.name', '=', 'Store Department')
        # ], limit=1)
        # Factory Manager find karo
        manager = self.env['hr.employee'].search([
            ('job_title', '=', 'Factory Manager'),
            ('department_id.name', '=', 'Factory')
        ], limit=1)

        email = manager.user_id.partner_id.email if manager.user_id else ''

        mail_values = {
            'subject': 'Weekly Production Summary',
            'body_html': body,
            'email_to': email,
        }

        self.env['mail.mail'].create(mail_values).send()


    # P&L Report
